# Generated by Django 3.2 on 2021-05-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210503_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.IntegerField(choices=[(0, 'American'), (1, 'French'), (2, 'Cafe'), (3, 'Southern'), (4, 'Italian'), (5, 'Mexican'), (6, 'BBQ'), (7, 'Ice Cream'), (8, 'Vietnamese'), (9, 'Chinese'), (10, 'Mediterranean'), (11, 'Cajun'), (12, 'Japanese'), (13, 'Seafood'), (14, 'Thai'), (15, 'Caribbean'), (16, 'Korean'), (17, 'Szechuan'), (18, 'Indian'), (19, 'Brazilian'), (20, 'Latin American')]),
        ),
    ]
