# Generated by Django 3.2 on 2021-05-03 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210503_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('name', 'category')},
        ),
    ]
