# Generated by Django 3.2 on 2021-05-04 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_restaurant_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('americanCount', models.IntegerField(default=0)),
                ('frenchCount', models.IntegerField(default=0)),
                ('cafeCount', models.IntegerField(default=0)),
                ('southernCount', models.IntegerField(default=0)),
                ('italianCount', models.IntegerField(default=0)),
                ('mexicanCount', models.IntegerField(default=0)),
                ('bbqCount', models.IntegerField(default=0)),
                ('icecreamCount', models.IntegerField(default=0)),
                ('vietCount', models.IntegerField(default=0)),
                ('chineseCount', models.IntegerField(default=0)),
                ('medCount', models.IntegerField(default=0)),
                ('cajunCount', models.IntegerField(default=0)),
                ('japaneseCount', models.IntegerField(default=0)),
                ('seaCount', models.IntegerField(default=0)),
                ('thaiCount', models.IntegerField(default=0)),
                ('carrCount', models.IntegerField(default=0)),
                ('koreanCount', models.IntegerField(default=0)),
                ('szechCount', models.IntegerField(default=0)),
                ('indianCount', models.IntegerField(default=0)),
                ('brazCount', models.IntegerField(default=0)),
                ('latinCount', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
