# Generated by Django 3.2 on 2021-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='americanCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bbqCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='brazCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cafeCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cajunCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='carrCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chineseCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='frenchCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='icecreamCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='indianCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='italianCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='japaneseCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='koreanCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latinCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mexicanCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='seaCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='southernCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='szechCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thaiCount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vietCount',
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_vec',
            field=models.TextField(default="{'preference_vec': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}"),
        ),
    ]
