# Generated by Django 3.2 on 2021-05-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210504_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference_vec',
            field=models.TextField(default='{"preference_vec": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}'),
        ),
    ]
