# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ResturantApp (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ResturantApp (iOS)
  pod 'LBTATools'  
  pod 'JGProgressHUD'
end

target 'ResturantApp (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ResturantApp (macOS)
  
end
